---
abstract: 'Plack PYX directory application.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::Object: 0
  Plack::Test: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-Directory-PYX
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  PYX::SGML::Tags: 0
  Plack::App::Directory: 0
  Tags::Output::Raw: 0
  Unicode::UTF8: 0
  perl: 5.8.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Plack-App-Directory-PYX
  homepage: https://github.com/michal-josef-spacek/Plack-App-Directory-PYX
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Plack-App-Directory-PYX
version: '0.03'
